# Generated by Django 3.0.2 on 2020-02-11 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_auto_20200211_0622'),
    ]

    operations = [
        migrations.AddField(
            model_name='drawing',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
